---
name: Catalyst-View-Chart-Strip
version: 0.04
author:
  - 'Brandon L Black, C<blblack@gmail.com>'
abstract: A Catalyst View for Chart::Strip graphics
license: perl
requires:
  Chart::Strip: 1.01
  UNIVERSAL::require: 0
build_requires:
  Test::More: 0
provides:
  Catalyst::Helper::View::Chart::Strip:
    file: lib/Catalyst/Helper/View/Chart/Strip.pm
  Catalyst::View::Chart::Strip:
    file: lib/Catalyst/View/Chart/Strip.pm
    version: 0.04
  Catalyst::View::Chart::Strip::Example:
    file: lib/Catalyst/View/Chart/Strip/Example.pm
generated_by: Module::Build version 0.2611
